[2024-05-29T14:52:37.616+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1_dag.extract_user scheduled__2024-05-28T00:00:00+00:00 [queued]>
[2024-05-29T14:52:37.802+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: 1_dag.extract_user scheduled__2024-05-28T00:00:00+00:00 [queued]>
[2024-05-29T14:52:37.817+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T14:52:37.818+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2024-05-29T14:52:37.832+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2024-05-29T14:52:39.844+0000] {taskinstance.py:1383} INFO - Executing <Task(SimpleHttpOperator): extract_user> on 2024-05-28 00:00:00+00:00
[2024-05-29T14:52:40.109+0000] {standard_task_runner.py:55} INFO - Started process 517 to run task
[2024-05-29T14:52:40.183+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', '1_dag', 'extract_user', 'scheduled__2024-05-28T00:00:00+00:00', '--job-id', '21', '--raw', '--subdir', 'DAGS_FOLDER/1_dag.py', '--cfg-path', '/tmp/tmpb889o6zt']
[2024-05-29T14:52:40.203+0000] {standard_task_runner.py:83} INFO - Job 21: Subtask extract_user
[2024-05-29T14:52:42.205+0000] {task_command.py:376} INFO - Running <TaskInstance: 1_dag.extract_user scheduled__2024-05-28T00:00:00+00:00 [running]> on host 4b56679d13b8
[2024-05-29T14:52:43.744+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_dag
AIRFLOW_CTX_TASK_ID=extract_user
AIRFLOW_CTX_EXECUTION_DATE=2024-05-28T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-05-28T00:00:00+00:00
[2024-05-29T14:52:43.757+0000] {http.py:121} INFO - Calling HTTP method
[2024-05-29T14:52:44.138+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2024-05-29T14:52:44.193+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2024-05-29T14:52:47.700+0000] {http.py:125} INFO - {"results":[{"gender":"female","name":{"title":"Mrs","first":"Luz","last":"Bahena"},"location":{"street":{"number":5905,"name":"Circuito Malasia"},"city":"Etucuaro","state":"Queretaro","country":"Mexico","postcode":94528,"coordinates":{"latitude":"28.2660","longitude":"172.6172"},"timezone":{"offset":"-3:00","description":"Brazil, Buenos Aires, Georgetown"}},"email":"luz.bahena@example.com","login":{"uuid":"9155954a-f549-44b3-9869-2dbfadddb9f5","username":"purpledog843","password":"gesperrt","salt":"xqLqQn2H","md5":"95413b8297ac6a021646c0946f6e96d0","sha1":"7914925bfe3ff8cb694754688a30738822707c15","sha256":"8016b6cdce3b0dcdf701b3376e16202cdd9b5049442cbe9a90c37ead4b5c0c76"},"dob":{"date":"1983-10-13T09:24:04.835Z","age":40},"registered":{"date":"2021-07-01T23:25:50.460Z","age":2},"phone":"(688) 866 9372","cell":"(628) 052 6327","id":{"name":"NSS","value":"70 95 82 9012 4"},"picture":{"large":"https://randomuser.me/api/portraits/women/63.jpg","medium":"https://randomuser.me/api/portraits/med/women/63.jpg","thumbnail":"https://randomuser.me/api/portraits/thumb/women/63.jpg"},"nat":"MX"}],"info":{"seed":"91bb1902668cd64d","results":1,"page":1,"version":"1.4"}}
[2024-05-29T14:52:47.702+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/http/operators/http.py", line 132, in execute
    return self.response_filter(response, **kwargs)
  File "/opt/airflow/dags/1_dag.py", line 55, in <lambda>
    response_filter = lambda response: json.load(response.text),
  File "/usr/local/lib/python3.7/json/__init__.py", line 293, in load
    return loads(fp.read(),
AttributeError: 'str' object has no attribute 'read'
[2024-05-29T14:52:52.095+0000] {taskinstance.py:1406} INFO - Marking task as FAILED. dag_id=1_dag, task_id=extract_user, execution_date=20240528T000000, start_date=20240529T145237, end_date=20240529T145252
[2024-05-29T14:52:53.383+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 21 for task extract_user ('str' object has no attribute 'read'; 517)
[2024-05-29T14:52:53.703+0000] {local_task_job.py:164} INFO - Task exited with return code 1
[2024-05-29T14:52:54.988+0000] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
